name: test

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ["18.x", "20.x", "22.x", "24.x"]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Restore node_modules cache
              uses: actions/cache/restore@v4
              id: node-cache-restore
              with:
                  path: node_modules
                  key: dependencies-node${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
            - name: Install dependencies
              run: npm ci
              if: steps.node-cache-restore.outputs.cache-hit != 'true'
            - name: Save node_modules cache
              uses: actions/cache/save@v4
              if: always() && steps.node-cache-restore.outputs.cache-hit != 'true'
              with:
                  path: node_modules
                  key: dependencies-node${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
            - name: Lint code
              run: npm run lint
            - name: Build code
              run: npm run build
            - name: Run tests
              run: npm test
